services:
  audit:
    container_name: audit-worker
    build:
      context: .
      dockerfile: ./apps/audit/Dockerfile
    restart: always
    ports:
      - ${AUDIT_WORKER_PORT}:${AUDIT_WORKER_PORT}
    environment:
      - REDIS_URL=${REDIS_URL}
      - AUDIT_QUEUE_NAME=${AUDIT_QUEUE_NAME}
      - AUDIT_DB_URL=${AUDIT_DB_URL}
      - LOG_LEVEL=${LOG_LEVEL}
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:5600/healthz']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
  mail:
    container_name: mail-worker
    build:
      context: .
      dockerfile: ./apps/mail/Dockerfile
    restart: always
    ports:
      - ${MAIL_WORKER_PORT}:${MAIL_WORKER_PORT}
    environment:
      - REDIS_URL=${REDIS_URL}
      - MAIL_QUEUE_NAME=${MAIL_QUEUE_NAME}
      - AUTH_DB_URL=${AUTH_DB_URL}
      - INFISICAL_URL=${INFISICAL_URL}
      - INFISICAL_ACCESS_TOKEN=${INFISICAL_ACCESS_TOKEN}
      - KMS_KEY_ID=${KMS_KEY_ID}
      - LOG_LEVEL=${LOG_LEVEL}
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:5601/healthz']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
