services:
  audit:
    container_name: audit
    build:
      context: .
      dockerfile: ./apps/audit/Dockerfile
    restart: always
    environment:
      - REDIS_URL=${REDIS_URL}
      - AUDIT_QUEUE_NAME=${AUDIT_QUEUE_NAME}
      - AUDIT_DB_URL=${AUDIT_DB_URL}
      - LOG_LEVEL=${LOG_LEVEL}
