# yaml-language-server: $schema=https://api.cerbos.dev/latest/cerbos/policy/v1/Policy.schema.json
# docs: https://docs.cerbos.dev/cerbos/latest/policies/resource_policies

apiVersion: api.cerbos.dev/v1
resourcePolicy:
  resource: Config
  version: default
  rules:
    - actions:
        - read
        - update
        - create
        - delete
      effect: EFFECT_ALLOW
      roles:
        - admin
        - owner
